# Correlación y regresión

Esta lección aborda las técnicas para estudiar la **relación entre dos variables numéricas**: primero la
correlación (cuantificar la fuerza y dirección de una asociación) y después la regresión (modelar y predecir
una variable a partir de otra). El enfoque es **procedimental**: entender qué se está midiendo, comprobar los
supuestos, ejecutar los procedimientos en R, leer los resultados y reportarlos.

La pregunta que organiza la lección es distinta de la de comparar grupos. Ya no se trata de "¿difieren estos
grupos en una variable?", sino de "¿varían estas dos cosas de forma conjunta, y cuánto?".

Se trabaja sobre una muestra de graduandos de nivel diversificado (ciclo anual), con dos variables de
resultado numéricas: `measure_mate` y `measure_lect` (medidas de desempeño en matemática y lectura, en una
escala continua centrada cerca de cero, donde los valores positivos indican mejor desempeño). La relación
entre ambas es el hilo conductor: es esperable que quien tiene mejor desempeño en una tienda a tenerlo también
en la otra, y eso es justo lo que la correlación y la regresión permiten precisar.

## Recorrido de la lección

1. **Correlación**: medir la fuerza y dirección de la relación entre dos variables numéricas (Pearson,
   Spearman, Kendall), con la comprobación de supuestos y el problema de las comparaciones múltiples.
2. **Regresión lineal simple**: modelar y predecir una variable a partir de otra, comprobar los supuestos e
   interpretar los coeficientes, los intervalos y las predicciones.
Incluye además una aclaración sobre las escalas Likert y cuándo es defendible tratarlas con métodos
paramétricos.

> **Por qué se usa una muestra.** Estas técnicas tienen dos usos. Uno es **descriptivo**: calcular la fuerza
> de una relación o la ecuación de una recta, lo que puede hacerse sobre cualquier conjunto de datos, sea una
> muestra o una población completa. El otro es **inferencial**: usar los valores p y los intervalos de
> confianza para generalizar de la muestra a la población. Esa parte inferencial solo tiene sentido cuando se
> observa una parte de la población, porque estima la incertidumbre de esa generalización. Si se dispusiera de
> los datos de todos los graduandos del país, la relación entre matemática y lectura simplemente sería la que
> se observa, sin incertidumbre que estimar. Aquí se trabaja con una muestra, con fines didácticos.

---

## 1. Preparación

Al leer el archivo conviene declarar de una vez los códigos que representan datos faltantes. Varias columnas
de esta base usan un punto (`"."`) para indicar ausencia de dato; si no se declara, R interpreta esas columnas
como texto. El argumento `na` de `read_csv()` lo resuelve desde la lectura.

```r
pacman::p_load(
  tidyverse,    # manipulación y gráficos
  janitor,      # clean_names()
  rstatix,      # correlaciones y pruebas en formato ordenado
  broom,        # convertir modelos en tablas ordenadas
  performance,  # diagnóstico de supuestos de modelos
  car,          # diagnósticos de regresión
  report,       # reporte automático en formato APA
  here
)

datos <- read_csv(
  here("Datos", "muestra_graduandos_anual.csv"),
  na = c("", "NA", ".")
) %>%
  clean_names()

datos <- datos %>%
  mutate(
    measure_mate  = as.numeric(measure_mate),
    measure_lect  = as.numeric(measure_lect),
    lectura_horas = as.numeric(lectura_horas)
  )
```

---

# Parte I — Correlación

## 2. Qué mide una correlación

Un coeficiente de correlación resume en un solo número la **fuerza** y la **dirección** de la relación entre
dos variables. Toma valores entre −1 y +1:

- El **signo** indica la dirección: positivo si las dos variables tienden a subir juntas, negativo si una sube
  cuando la otra baja.
- La **magnitud** indica la fuerza: cerca de 0 no hay relación; cerca de ±1, la relación es casi perfecta.

Antes de calcular nada, conviene **mirar los datos**. La correlación comprime una nube de puntos en un número,
y ese resumen puede engañar si no se observa la forma de la nube.

```r
ggplot(datos, aes(x = measure_mate, y = measure_lect)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  labs(title = "Relación entre desempeño en matemática y lectura",
       x = "Matemática", y = "Lectura")
```

El diagrama de dispersión muestra una nube que asciende de izquierda a derecha: los estudiantes con mejor
desempeño en matemática tienden a tenerlo también en lectura. La pregunta es cuán fuerte es esa tendencia.

> **Correlación no implica causalidad.** Que dos variables varíen juntas no significa que una cause la otra.
> Ambas pueden estar impulsadas por un tercer factor (aquí, por ejemplo, el nivel socioeconómico o la calidad
> del centro afectan a la vez a matemática y lectura). La correlación describe una asociación; establecer una
> causa requiere un diseño distinto, experimental o cuasi-experimental.

---

## 3. Coeficiente de Pearson (paramétrico)

El coeficiente de Pearson mide la fuerza de la relación **lineal** (es decir, en línea recta) entre dos
variables numéricas. Es el más usado, y su hipótesis nula es que no existe correlación lineal en la población
(ρ = 0).

### 3.1 Comprobación de supuestos (antes de calcular)

Conviene distinguir dos usos del coeficiente, porque no exigen lo mismo.

**Para describir la asociación** (el valor de r en sí), lo que importa es que la relación sea **lineal** y que
no haya **valores atípicos** que la distorsionen. La linealidad no se "asume": se verifica mirando el diagrama
de dispersión. Escribir "se asume linealidad" sin observar la nube de puntos es un error frecuente, porque la
linealidad es justamente lo que decide si Pearson es la medida adecuada. Si la relación es fuerte pero curva
(en forma de U, por ejemplo), r puede dar cerca de cero y esconderla; y un solo punto extremo puede inflar o
desinflar el coeficiente. El diagrama es la única herramienta que revela ambos problemas de un vistazo, y por
eso es un paso obligatorio, no opcional.

**Para la inferencia** (el valor p y el intervalo de confianza de `cor.test`), se añade el supuesto de
**normalidad bivariada**: la fórmula que produce esos valores se dedujo suponiendo que las dos variables
siguen conjuntamente una distribución normal. En la práctica se revisa la normalidad de cada variable por
separado. Este supuesto pierde importancia en muestras grandes gracias al teorema central del límite, pero
esa protección es parcial y condicionada, no un salvoconducto: el recuadro siguiente precisa qué cubre y qué
no, porque es una de las ideas peor entendidas de toda la estadística aplicada.

Comprobación de los tres puntos:

```r
# 1. Linealidad y atípicos: comparar una curva flexible con la recta
ggplot(datos, aes(x = measure_mate, y = measure_lect)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "loess", color = "blue", se = FALSE) +   # curva que sigue los datos
  geom_smooth(method = "lm",    color = "red",  se = FALSE)      # recta
# Si la curva azul (loess) se aparta de la recta roja, la relación no es lineal.

# 2. Normalidad de cada variable (relevante sobre todo en muestras pequeñas)
shapiro.test(datos$measure_mate)
shapiro.test(datos$measure_lect)

# 3. Atípicos: valores con puntuación z fuera de ±3
datos %>%
  filter(abs(scale(measure_mate)) > 3 | abs(scale(measure_lect)) > 3)
```

La curva **loess** sigue los datos sin imponerles una recta; superponerla a la recta de regresión es la forma
más directa de juzgar la linealidad: si ambas casi coinciden, la relación es lineal. En estos datos lo son, de
modo que Pearson es apropiado.

### El teorema central del límite: qué protege y qué no

En el contexto donde se aplica la estadística en educación y psicología circula un atajo peligroso: *"tengo
más de 30 datos, el teorema central del límite me protege, no necesito comprobar supuestos"*. Esa frase usa
un teorema real para justificar saltarse el diagnóstico, y descansa en varios malentendidos que conviene
deshacer uno por uno.

**Qué dice realmente el teorema.** El teorema central del límite (TCL) afirma que, al tomar muestras y
calcular su **media**, la distribución de esas medias se aproxima a una normal conforme crece el tamaño de
muestra, **aunque la variable original no sea normal**. Conviene ser preciso con el lenguaje: el teorema no
"normaliza" nada ni "actúa" sobre los datos. Un teorema es una afirmación matemática demostrada; lo que este
**establece** es que la distribución de la media muestral, sobre muestras repetidas, se aproxima a una normal
al crecer n. No cambia los datos: describe un hecho sobre cómo se comporta la media. Por eso la prueba t o la
regresión siguen siendo válidas con datos no normales: lo que la fórmula necesita que sea normal no son los
datos, sino la distribución del estadístico (concepto que se explica en el apartado siguiente), y el TCL
garantiza que esa distribución se aproxima a la normal cuando n es suficiente.

**Qué es "la distribución del estadístico".** Esta idea es abstracta, así que conviene una imagen concreta.
Cuando se hace un estudio, se obtiene **una** muestra y se calcula con ella un número: una media, una t, una
correlación. Ese número es el **estadístico**. Ahora, un experimento mental: imagínese que el estudio se
repitiera muchísimas veces, cada vez con una muestra nueva del mismo tamaño extraída de la misma población.
Cada repetición daría un valor **algo distinto** del estadístico, por el simple azar de a quién le tocó entrar
en cada muestra. Si se anotaran todos esos valores, formarían una distribución: la **distribución muestral del
estadístico**. No es la distribución de los datos, sino la de un resumen calculado sobre muestras repetidas.

Puede verse con la variable de matemática. Tomando muchas muestras de 50 estudiantes y calculando la media de
cada una:

```r
set.seed(3)
x <- na.omit(datos$measure_mate)
medias <- replicate(5000, mean(sample(x, 50)))

mean(medias)      # ~0.24 : el promedio de las medias coincide con la media poblacional
sd(medias)        # ~0.15 : su dispersión es el "error estándar"
skewness(medias)  # ~0.24 : casi simétrica...
skewness(x)       # ~1.98 : ...aunque los datos originales son muy asimétricos
```

Esas 5000 medias van de −0.20 a 1.01, se agrupan en torno a la media real y forman una distribución
**casi simétrica**, pese a que la variable original tiene una asimetría de 1.98. Eso es lo que garantiza el
TCL, y es lo que importa: el valor p se calcula comparando el estadístico observado contra **esta**
distribución (la de los valores que tomaría por azar si la hipótesis nula fuera cierta), no contra la
distribución de los datos crudos. Por eso la normalidad que la prueba necesita es la de este objeto, no la de
la variable.

**Primer malentendido: el umbral de 30 no es universal.** El famoso "n ≥ 30" no es una ley; es una regla de
bolsillo que solo funciona con asimetrías moderadas. Cuanto más asimétrica es la variable, más casos hacen
falta. Puede verse con la propia variable de matemática de esta muestra, que tiene una asimetría de 1.98:

```r
set.seed(11)
x <- na.omit(datos$measure_mate)

simular_media <- function(n, reps = 3000) replicate(reps, mean(sample(x, n)))

skewness(simular_media(30))    # asimetría de la media con n = 30
#> [1] 0.28   (la media muestral TODAVÍA no es simétrica)
skewness(simular_media(100))
#> [1] 0.19
skewness(simular_media(300))
#> [1] 0.07   (recién aquí la media se comporta como normal)
```

Con esta variable, a los 30 casos la media muestral **aún no** es normal; hace falta llegar a unos 300. Y con
variables muy asimétricas, frecuentes en educación (número de ausencias, de repitencias, ingresos del hogar,
conteos con muchos ceros), ni **mil** casos bastan para normalizar la media. El "30" da una falsa sensación
de seguridad que depende por completo de la forma de los datos, y esa forma solo se conoce mirándola.

**Segundo malentendido: el TCL solo cubre un supuesto, no todos.** Aun cuando protege la normalidad, no dice
absolutamente nada sobre los demás supuestos. Un tamaño de muestra grande **no** corrige:

- La **falta de independencia.** Si las observaciones están correlacionadas (estudiantes del mismo aula,
  mediciones repetidas), el error estándar queda mal calculado y más datos solo consolidan el error. El TCL
  no interviene aquí.
- La **heterocedasticidad.** El TCL habla de la media, no de la varianza. Si la dispersión difiere entre
  grupos o a lo largo de la predictora, n grande no lo arregla.
- Los **valores atípicos influyentes.** Un solo error de captura puede torcer un resultado por mucho que
  sobren datos. Basta un ejemplo: con 40 observaciones normales alrededor de 50, la prueba t contra 50 da
  p = .93; al cambiar **un** valor por 500 (un error de digitación), la media sube a 61.6 y la conclusión se
  desmorona (p = .31). Los 40 casos no protegieron nada.

**Tercer malentendido: normalidad de la variable frente a normalidad del estadístico.** El TCL justifica no
preocuparse por la normalidad de la **variable**, pero eso no equivale a "no comprobar nada". Sigue siendo
necesario revisar la linealidad, los atípicos, la independencia y la homocedasticidad, que son supuestos
distintos y que el tamaño de muestra no toca.

**La concepción correcta.** Conviene enunciarla con cuidado, porque es fácil deslizarse hacia la licencia que
se quiere evitar. El TCL **no autoriza a dejar de mirar la normalidad**. La forma de los datos y de los
residuos se examina **siempre**, con gráficos (histograma, Q-Q) y estadísticos de forma; ese paso no se
omite nunca. Lo único que cambia con una muestra grande es la **decisión** que se toma ante lo que se ve: una
desviación moderada de la normalidad, que en una muestra pequeña obligaría a cambiar de método, en una muestra
grande y con asimetría no extrema puede tolerarse sin comprometer la inferencia.

La diferencia es sutil pero decisiva: no es "tengo muchos datos, no compruebo la normalidad", sino "compruebo
la normalidad como siempre, y al interpretar lo que encuentro tengo en cuenta que, con esta cantidad de datos y
esta asimetría, una desviación moderada no invalida la prueba". Se mira igual; lo que cambia es el criterio con
que se actúa. Y esto vale solo para la normalidad: la linealidad, la independencia, la homocedasticidad y los
atípicos se comprueban y se atienden con el mismo rigor, tenga la muestra el tamaño que tenga.

### 3.2 Cálculo e interpretación

```r
cor.test(datos$measure_mate, datos$measure_lect)
#>
#>  Pearson's product-moment correlation
#>
#> t = 34.83, df = 3255, p-value < 2.2e-16
#> 95 percent confidence interval:
#>  0.496  0.546
#> sample estimates:
#>       cor
#> 0.5214
```

La correlación es r = .52, positiva y fuerte. El intervalo de confianza [0.496, 0.546] indica el rango
plausible del valor poblacional, y al no incluir el cero confirma que la relación es significativa.

**El coeficiente de determinación.** Elevar la correlación al cuadrado (r² = .52² = .27) da la **proporción de
varianza compartida**: cerca del 27 % de la variación en lectura se asocia con la variación en matemática (y a
la inversa). Es una forma más intuitiva de comunicar la fuerza: no que "la relación es 0.52", sino que "una
variable explica el 27 % de la variabilidad de la otra".

Como referencia orientativa para interpretar la magnitud:

| \|r\|         | Interpretación habitual |
|---------------|--------------------------|
| 0.10 a 0.29   | Débil                    |
| 0.30 a 0.49   | Moderada                 |
| 0.50 o más    | Fuerte                   |

> **Estas tablas son convenciones, no leyes.** Circulan muchas versiones distintas de este tipo de tabla, con
> cortes diferentes, y ninguna tiene un sustento universal. La más citada proviene de Cohen (1988), pero el
> propio Cohen advirtió que sus umbrales eran orientaciones para cuando no hubiera nada mejor, no criterios
> rígidos. Lo que cuenta como una correlación "fuerte" depende por completo del campo: en física una r de .60
> puede ser decepcionante, mientras que en investigación educativa o psicológica, donde el comportamiento
> humano es multicausal, una r de .30 puede ser un hallazgo relevante. La recomendación práctica es no
> anclarse en la etiqueta, sino interpretar la magnitud en el contexto del fenómeno estudiado y de lo
> reportado por otros estudios comparables, y acompañar siempre r con r² (la varianza compartida) para
> comunicar el tamaño de forma más tangible.

**Cómo reportarlo.** Se calculó el coeficiente de correlación de Pearson entre el desempeño en matemática y en
lectura. Se observó una correlación positiva, fuerte y significativa, r(3255) = .52, p < .001, IC 95 %
[.50, .55]. El desempeño en matemática explicó aproximadamente el 27 % de la varianza en lectura.

> Los grados de libertad de una correlación son n − 2 (aquí 3257 − 2 = 3255).

---

## 4. Coeficientes de Spearman y Kendall (no paramétricos)

Cuando la relación no es lineal, hay atípicos influyentes o las variables son ordinales, se usan coeficientes
basados en **rangos**, es decir, en las posiciones ordenadas de los datos en lugar de sus valores crudos.

### El coeficiente de Spearman

Es el de Pearson calculado sobre los rangos. La consecuencia de trabajar con posiciones es que Spearman ya no
mide relación lineal, sino **monotónica**. Conviene precisar el término, porque es la clave:

Una relación es **monotónica** cuando, al aumentar una variable, la otra se mueve siempre en la misma
dirección (siempre sube, o siempre baja), aunque el ritmo no sea constante. Ejemplo: a más horas de estudio,
más rendimiento; puede que las primeras horas rindan mucho y las últimas poco (la relación se "aplana"), pero
nunca se invierte. Eso es monotónico pero **no** lineal: no es una recta, es una curva que siempre asciende.
Pearson, que busca una recta, subestimaría esa relación; Spearman, que solo mira si las posiciones suben
juntas, la capta bien.

En resumen: **toda relación lineal es monotónica, pero no toda relación monotónica es lineal**. Spearman cubre
el caso más amplio.

```r
cor.test(datos$measure_mate, datos$measure_lect, method = "spearman")
#>  rho = 0.502, p-value < 2.2e-16
```

En estos datos, Spearman (rho = .50) es casi idéntico a Pearson (.52). Esa coincidencia es informativa:
cuando ambos son parecidos, la relación es efectivamente lineal y sin atípicos que la distorsionen. Si
difirieran mucho, esa discrepancia sería una señal de no linealidad o de valores extremos.

### El coeficiente tau de Kendall

Es otra medida basada en rangos, preferible cuando hay **muchos empates** (valores repetidos) o la muestra es
pequeña. Se interpreta a partir de la **concordancia entre pares de observaciones**, una idea que conviene
explicar porque no es evidente.

Se toman dos estudiantes cualesquiera y se comparan en las dos variables. El par es **concordante** si quien
tiene más matemática tiene también más lectura (las dos comparaciones apuntan en la misma dirección). Es
**discordante** si quien tiene más matemática tiene menos lectura (apuntan en direcciones opuestas). Kendall
recorre todos los pares posibles de la muestra y calcula:

$$\tau = \frac{(\text{pares concordantes}) - (\text{pares discordantes})}{\text{total de pares}}$$

Si todos los pares son concordantes, tau = 1 (relación positiva perfecta); si todos son discordantes,
tau = −1; si hay tantos de un tipo como del otro, tau = 0. Un valor de tau = 0.37, como en estos datos,
significa que los pares concordantes superan a los discordantes por 37 puntos porcentuales del total: hay una
clara tendencia a que quien puntúa alto en una puntúe alto en la otra, pero con bastantes excepciones.

```r
cor.test(datos$measure_mate, datos$measure_lect, method = "kendall")
#>  tau = 0.366, p-value < 2.2e-16
```

Los valores de tau suelen ser menores que los de Spearman para los mismos datos (aquí 0.37 frente a 0.50), no
porque la relación sea más débil, sino porque miden cosas distintas: tau es una proporción de concordancia y
Spearman es una correlación de rangos. No son directamente comparables entre sí.

### Qué significa "muestra pequeña"

Varias veces se ha dicho que ciertos supuestos importan más en muestras pequeñas. Conviene un orden de
magnitud, aunque no exista un umbral exacto:

- Por debajo de unos **30 casos**, la muestra es claramente pequeña: el teorema central del límite ofrece poca
  protección (y menos aún si la variable es asimétrica, como precisa el recuadro de la sección 3), la normalidad
  importa de verdad y los métodos basados en rangos (Spearman, Kendall) o las versiones exactas ganan atractivo.
- Entre **30 y 100** hay una zona intermedia donde conviene revisar los supuestos con cuidado.
- Por encima de unos **100 casos**, y desde luego con los miles de esta muestra, la inferencia paramétrica es
  robusta frente a desviaciones moderadas de la normalidad.

Son órdenes de magnitud orientativos, no reglas rígidas: una asimetría muy pronunciada o un atípico influyente
pueden exigir más casos, y un tamaño de efecto grande puede detectarse con menos.

**Cuándo usar cada uno:** Pearson para variables cuantitativas con relación lineal; Spearman para relaciones
monotónicas, datos ordinales o presencia de atípicos; Kendall para datos ordinales con muchos empates o
muestras pequeñas.

---

## 5. Matriz de correlaciones

Cuando hay varias variables numéricas, se examinan todas sus correlaciones a la vez. Se añaden dos predictores:
`lectura_horas` (horas de lectura, ordinal de 0 a 4) y `fm_grado_alcanzo_mama_reco` (grado de escolaridad
alcanzado por la madre, de 1 a 4).

```r
vars <- datos %>%
  select(measure_mate, measure_lect, lectura_horas, fm_grado_alcanzo_mama_reco)

cor(vars, use = "complete.obs")
#>                             measure_mate measure_lect lectura_horas   mama
#> measure_mate                       1.000        0.535        -0.026  0.154
#> measure_lect                       0.535        1.000        -0.022  0.273
#> lectura_horas                     -0.026       -0.022         1.000  0.053
#> fm_grado_alcanzo_mama_reco         0.154        0.273         0.053  1.000
```

Para visualizar el patrón de un vistazo, un mapa de calor:

```r
pacman::p_load(corrplot)
cor(vars, use = "complete.obs") %>%
  corrplot(method = "color", addCoef.col = "black", type = "upper")
```

### El problema de las comparaciones múltiples

Este punto es importante y suele pasarse por alto. Una matriz de correlaciones no calcula una prueba, sino
**muchas a la vez**: con 4 variables hay 6 pares; con 10 variables, 45. Y cada prueba individual tiene, por
diseño, una probabilidad del 5 % de dar un "falso positivo" (declarar significativa una correlación que en la
población es cero). Al hacer muchas pruebas, esos riesgos se acumulan.

El cálculo es directo: si se realizan 6 pruebas independientes y cada una tiene un 95 % de probabilidad de
**no** dar un falso positivo, la probabilidad de que **ninguna** lo dé es 0.95⁶ = 0.735. Es decir, hay un
**26 %** de probabilidad de obtener al menos un falso positivo en la matriz, muy por encima del 5 % que se
cree estar controlando. Con 45 pruebas (10 variables), esa probabilidad supera el 90 %: es casi seguro
encontrar "algo significativo" aunque no haya nada.

La solución es **ajustar los valores p** para tener en cuenta el número de pruebas. El método de Holm es uno de
los más usados: ordena los valores p y exige umbrales progresivamente más estrictos.

```r
# Matriz de valores p SIN ajustar
rstatix::cor_pmat(vars)

# Valores p AJUSTADOS por comparaciones múltiples (método de Holm)
matriz_p <- cor_mat(vars) %>%
  cor_get_pval()

# rstatix también reporta la significancia ya ajustada al mostrar la matriz
cor_mat(vars) %>% cor_mark_significant()
```

En estos datos el ajuste cambia poco las conclusiones fuertes, pero disciplina las débiles. Las correlaciones
de `lectura_horas` con matemática (r = −.026) y con lectura (r = −.022) no son significativas ni antes ni
después del ajuste (sus valores p rondan .18 y .25). En cambio, la correlación entre horas de lectura y
escolaridad materna, que sin ajustar tenía p = .006, tras el ajuste de Holm sube a p = .017: sigue siendo
significativa, pero el ajuste la vuelve más creíble al haberla evaluado en el contexto de todas las pruebas
realizadas.

La regla práctica: cuando se interpreta una matriz completa de correlaciones, se reportan los valores p
ajustados, no los originales.

---

# Parte II — Regresión lineal

## 6. De la correlación a la regresión

La correlación dice **cuán fuerte** es la relación; la regresión da un paso más y la **modela**: construye una
ecuación que permite predecir una variable (la **respuesta** o dependiente) a partir de otra (la **predictora**
o independiente). Mientras la correlación es simétrica (la de A con B es igual que la de B con A), la regresión
no lo es: distingue qué variable se predice y cuál predice.

La regresión lineal simple ajusta una **recta** a la nube de puntos, que se escribe así:

$$y = \beta_0 + \beta_1 x + \varepsilon$$

donde $\beta_0$ es el **intercepto** (el valor predicho de $y$ cuando $x = 0$), $\beta_1$ es la **pendiente**
(cuánto cambia $y$, en promedio, por cada unidad que aumenta $x$) y $\varepsilon$ es el **error**.

### Qué es ese "más épsilon" que luego desaparece

Una confusión habitual: la fórmula incluye $+\varepsilon$, pero al ajustar el modelo en R ese término no
aparece por ningún lado y parece no tener valor. La explicación aclara de paso qué es una regresión.

La fórmula con $\varepsilon$ describe la **realidad**: el valor real de $y$ de cada persona es igual a la parte
que la recta predice ($\beta_0 + \beta_1 x$) **más** una desviación propia de esa persona, que la recta no
captura. Ese $\varepsilon$ es el **error** de cada individuo: la distancia vertical entre el punto real y la
recta. Como cada persona tiene el suyo, $\varepsilon$ no es un número único, sino una variable entera (son los
**residuos** de los que se habla más adelante).

Cuando se ajusta el modelo, R estima $\beta_0$ y $\beta_1$ (los dos números que definen la recta) precisamente
buscando la recta que hace esos errores lo más pequeños posible en conjunto. Por eso en la salida solo se ven
$\beta_0$ y $\beta_1$: son lo que el modelo *estima*. El $\varepsilon$ no desaparece; se transforma en los
residuos, que se examinan aparte para comprobar los supuestos. Dicho de otro modo: la fórmula teórica lleva
$\varepsilon$ porque reconoce que ninguna recta pasa exactamente por todos los puntos; el ajuste produce los
coeficientes, y los errores quedan guardados como residuos.

En esta lección se modela el desempeño en lectura (`measure_lect`) a partir del de matemática (`measure_mate`).

---

## 7. Comprobación de supuestos de la regresión

Igual que en la correlación, los supuestos se comprueban **antes** de interpretar el modelo, y recaen sobre los
**residuos** (los errores individuales que quedan tras ajustar la recta), no sobre las variables en bruto.
Primero se ajusta el modelo, porque los residuos se obtienen de él, y enseguida se diagnostica.

```r
modelo <- lm(measure_lect ~ measure_mate, data = datos)
```

La regresión lineal descansa sobre cuatro supuestos, que suelen recordarse con el acrónimo **LINE**:
**L**inealidad, **I**ndependencia de las observaciones, **N**ormalidad de los residuos y **E**quidad de
varianzas (homocedasticidad, es decir, que la dispersión de los residuos sea pareja).

La forma más rápida de revisarlos es el conjunto de gráficos de diagnóstico. La instrucción `plot(modelo)`
produce cuatro gráficos; se disponen en una cuadrícula de 2×2 con `par(mfrow = ...)` para verlos juntos. A cada
uno de esos cuatro recuadros se le llama aquí **gráfico** (o recuadro):

```r
par(mfrow = c(2, 2))   # organiza los cuatro gráficos en una cuadrícula 2x2
plot(modelo)
par(mfrow = c(1, 1))   # restaura la disposición normal

# Alternativa moderna, con guías interpretativas incorporadas
performance::check_model(modelo)
```

**Linealidad y homocedasticidad** (primer gráfico, "Residuals vs Fitted", residuos contra valores predichos):
los puntos deben repartirse sin forma alrededor de la línea horizontal. Una curva señala que la relación no es
lineal; una forma de embudo (que se abre o se cierra) señala que la varianza no es constante.

```r
# Prueba formal de homocedasticidad (Breusch-Pagan)
performance::check_heteroscedasticity(modelo)
lmtest::bptest(modelo)
#>  BP = 251.63, df = 1, p-value < 2.2e-16
```

La prueba de Breusch-Pagan tiene como hipótesis nula que la varianza de los residuos es constante. Aquí rechaza
(p < .001): hay **heterocedasticidad**, la dispersión de los residuos no es pareja. Es un hallazgo frecuente
con datos reales, y el apartado 7.1 explica qué hacer.

**Normalidad de los residuos** (segundo gráfico, el Q-Q, que compara los residuos con lo que se esperaría si
fueran normales):

```r
performance::check_normality(modelo)
shapiro.test(residuals(modelo))
#>  W = 0.9867, p-value = 5.7e-17
```

Los residuos se apartan algo de la normalidad (asimetría 0.25, curtosis 1.31), aunque de forma leve. Con más de
3000 casos y una asimetría tan moderada, el teorema central del límite cubre esta desviación concreta (según lo
explicado en el recuadro de la sección 3), de modo que la no-normalidad de los residuos no invalida el modelo.
Esto no exime de revisar los otros supuestos: la heterocedasticidad detectada arriba sí requiere atención, y el
tamaño de muestra no la corrige.

**Independencia** (los residuos no deben estar correlacionados entre sí, algo relevante sobre todo cuando los
datos tienen un orden temporal):

```r
car::durbinWatsonTest(modelo)
#>  D-W Statistic = 1.808     (valores cercanos a 2 indican independencia)
```

### 7.1 Qué hacer cuando un supuesto falla

El diagnóstico dejó un caso realista: heterocedasticidad presente y leve no-normalidad. Las respuestas
habituales, según el supuesto que falle:

- **Errores estándar robustos.** La heterocedasticidad no sesga los coeficientes (la pendiente sigue siendo
  correcta); lo que distorsiona son sus errores estándar y, con ellos, los valores p e intervalos. La solución
  es corregir esos errores estándar sin cambiar el modelo:

```r
pacman::p_load(sandwich, lmtest)
coeftest(modelo, vcov = vcovHC(modelo, type = "HC3"))
```

- **Transformar la variable respuesta** (por ejemplo, aplicando logaritmo) puede corregir a la vez la no
  linealidad y la heterocedasticidad cuando la respuesta está muy sesgada.
- **Regresión robusta** (`MASS::rlm()`) reduce la influencia de los valores atípicos sobre la recta.

### 7.2 Observaciones influyentes

No todos los puntos pesan igual en la recta. Un valor extremo, sobre todo en la dirección de la predictora,
puede "arrastrar" la pendiente hacia sí. La **distancia de Cook** cuantifica cuánto cambiaría el modelo
completo si se eliminara cada observación:

```r
performance::check_outliers(modelo)
plot(modelo, which = 4)     # gráfico de la distancia de Cook
```

Un punto con distancia de Cook alta merece revisión: conviene comprobar si es un error de captura o un caso
legítimo, y valorar si el modelo cambia sustancialmente al excluirlo.

---

## 8. Ajustar y leer el modelo

Comprobados los supuestos, se interpreta el modelo. La **hipótesis nula de la regresión** es que la pendiente
poblacional es cero (β₁ = 0), lo que equivale a decir que la predictora no aporta información sobre la
respuesta: conocer la matemática de alguien no ayudaría en nada a predecir su lectura, y la mejor predicción
seguiría siendo simplemente el promedio general. Rechazar esa hipótesis es concluir que sí existe una relación.

```r
summary(modelo)
#>
#> Coefficients:
#>              Estimate Std. Error t value Pr(>|t|)
#> (Intercept)   0.11189    0.01301    8.60   <2e-16 ***
#> measure_mate  0.42433    0.01218   34.83   <2e-16 ***
#>
#> Residual standard error: 0.7428 on 3255 degrees of freedom
#> Multiple R-squared:  0.2715,  Adjusted R-squared:  0.2713
#> F-statistic:  1213 on 1 and 3255 DF,  p-value: < 2.2e-16
```

Cómo se lee esta salida, pieza por pieza:

**La pendiente (`measure_mate` = 0.424).** Por cada punto que aumenta el desempeño en matemática, el de lectura
predicho aumenta en promedio 0.424 puntos. Es el número central del modelo: cuantifica la relación en la escala
de las variables. Su valor p (columna `Pr(>|t|)`, aquí < .001) contrasta la hipótesis nula de pendiente cero; al
ser significativo, se concluye que matemática sí aporta información sobre lectura.

**El intercepto (0.112).** El valor predicho de lectura cuando matemática vale 0. Como estas medidas están
centradas cerca de cero, el intercepto es interpretable aquí; en otras escalas donde x = 0 no tiene sentido
(como predecir peso a partir de una estatura de 0 cm), el intercepto es solo el anclaje matemático de la recta
y no se interpreta.

**R² (0.272).** La proporción de la varianza de la lectura que el modelo explica: 27 %. Coincide con el cuadrado
de la correlación de Pearson, porque en regresión simple son lo mismo. El **R² ajustado** penaliza por el número
de predictores y es el que se usa para comparar modelos con distinto número de variables (relevante en la
lección de análisis multivariado).

**El error estándar residual (0.743).** La dispersión típica de los puntos alrededor de la recta, en las unidades
de la respuesta. Da una idea de cuánto se equivoca el modelo, en promedio, al predecir.

**El estadístico F y su valor p (última línea).** Contrastan si el modelo, tomado como un todo, explica una parte
de la variabilidad de la respuesta mayor que la que cabría esperar por azar. La hipótesis nula asociada es que
**todos** los coeficientes de las predictoras valen cero a la vez (que el modelo completo no sirve para nada). En
regresión simple, donde hay una sola predictora, ese contraste global coincide exactamente con el de la
pendiente, así que el valor p de la F y el de la pendiente son idénticos. La F cobra importancia propia en la
regresión múltiple, donde resume en un solo contraste el aporte conjunto de todos los predictores.

### 8.1 Intervalos de confianza de los coeficientes

El valor p dice si la pendiente es distinta de cero, pero no cuánto vale. El intervalo de confianza responde
esa segunda pregunta, y por eso suele ser más informativo.

```r
confint(modelo)
#>                  2.5 %    97.5 %
#> (Intercept)  0.0864    0.1374
#> measure_mate 0.4005    0.4482
```

El intervalo de la pendiente, [0.40, 0.45], se lee así: **el valor real de la pendiente en la población se
sitúa, de forma compatible con los datos observados, entre 0.40 y 0.45**. De ahí se extraen tres lecturas:

- **Decisión:** como el intervalo no incluye el cero, la pendiente es significativamente distinta de cero (la
  misma información que el valor p, pero en la escala de la variable).
- **Magnitud:** el efecto de la matemática sobre la lectura está entre 0.40 y 0.45 puntos por cada punto; es un
  efecto sustancial y bien acotado.
- **Precisión:** el intervalo es estrecho, lo que indica una estimación precisa. Un intervalo ancho (por
  ejemplo, [0.05, 0.80]) señalaría mucha incertidumbre sobre el tamaño real del efecto, aunque fuera
  significativo.

### 8.2 Coeficientes en formato ordenado

El paquete `broom` convierte la salida en una tabla, cómoda para exportar o graficar:

```r
broom::tidy(modelo, conf.int = TRUE)
#> # A tibble: 2 × 7
#>   term         estimate std.error statistic  p.value conf.low conf.high
#>   <chr>           <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)     0.112    0.0130      8.60 ...       0.0864    0.137
#> 2 measure_mate    0.424    0.0122     34.8  ...       0.400     0.448

broom::glance(modelo)   # una fila con R², AIC, F, etc.
```

**Cómo reportarlo.** Se realizó un análisis de regresión lineal simple para evaluar en qué medida el desempeño
en matemática predice el de lectura. La regresión fue significativa, F(1, 3255) = 1213, p < .001, con un R² de
.27 (el modelo explicó el 27 % de la varianza en lectura). La ecuación fue: lectura = 0.11 + 0.42 × (matemática);
por cada punto adicional en matemática, el puntaje de lectura predicho aumentó 0.42 puntos (IC 95 % [0.40, 0.45]).

> Cuando la regresión no es significativa, no tiene sentido interpretar la ecuación ni la pendiente: el reporte
> se detiene tras el valor p y, opcionalmente, el R².

---

## 9. Usar el modelo para predecir

Ajustado el modelo, `predict()` genera predicciones para nuevos valores de la predictora, con su intervalo.

```r
nuevos <- tibble(measure_mate = c(-1, 0, 1, 2))

# Intervalo de confianza: para la MEDIA predicha (más estrecho)
predict(modelo, newdata = nuevos, interval = "confidence")

# Intervalo de predicción: para una observación INDIVIDUAL (más ancho)
predict(modelo, newdata = nuevos, interval = "prediction")
```

Conviene distinguir los dos intervalos, porque se confunden a menudo:

- El **intervalo de confianza** estima dónde está la *media* de lectura de todos los estudiantes con cierto
  puntaje de matemática. Es estrecho.
- El **intervalo de predicción** estima el puntaje de *un estudiante concreto*, e incorpora además la variación
  individual, por lo que es mucho más ancho. Para anticipar un caso particular, este es el correcto.

---

## 9.1 Una aclaración necesaria: escalas Likert y la vía paramétrica

En educación y psicología, la variable que se quiere modelar suele provenir de una **escala Likert** (un
conjunto de ítems con respuestas ordenadas del tipo "Muy en desacuerdo … Muy de acuerdo"). Sobre esto circula
una objeción tajante que conviene abordar de frente, porque lleva a decisiones equivocadas: *"los ítems Likert
son ordinales, así que no se puede usar la vía paramétrica (t, ANOVA, regresión lineal); hay que ir siempre a
lo no paramétrico o a modelos ordinales"*.

Esa afirmación mezcla dos situaciones que son muy distintas, y de esa mezcla nace el error.

**Un ítem aislado sí es ordinal.** Una sola pregunta con cinco opciones ordenadas es, en efecto, una variable
ordinal con pocas categorías: nada garantiza que la distancia entre "Muy en desacuerdo" y "En desacuerdo" sea
igual que entre "De acuerdo" y "Muy de acuerdo". Tratar un ítem suelto como si fuera numérico es discutible, y
ahí la objeción tiene parte de razón.

**Pero un puntaje sumado no es un ítem.** Lo que casi nunca se analiza es el ítem individual, sino el
**puntaje total** que resulta de **sumar (o promediar) muchos ítems**. Y esa suma es una transformación que
cambia la naturaleza de la variable. Un total construido con quince o veinte ítems ya no tiene cinco
categorías, sino decenas de valores posibles; su distribución se aproxima a la continua, y la teoría de la
medición muestra que, bajo condiciones razonables, ese puntaje se comporta como una variable de intervalo. En
otras palabras: **al sumar, se deja de tener una variable ordinal de pocas categorías y se pasa a tener un
puntaje cuasi-continuo**. La objeción "es ordinal" se aplicaba al ítem, no al total.

Por eso, **cuando la variable a modelar es un puntaje de escala (suma o promedio de ítems), la regresión
lineal, la t y el ANOVA son plenamente defendibles.** No es un atajo ni una licencia: es el reconocimiento de
que la sumatoria transformó la variable. De hecho, décadas de estudios de simulación respaldan que estos
métodos aplicados a puntajes de escala conservan bien sus propiedades, incluso cuando cada ítem por separado
es ordinal.

Dónde poner el límite, en la práctica:

| La variable a modelar es…                                        | Vía razonable                          |
|------------------------------------------------------------------|-----------------------------------------|
| Un puntaje de escala (suma/promedio de varios ítems, muchos valores) | Regresión lineal / t / ANOVA (paramétrica) |
| Un solo ítem ordinal con pocas categorías                        | Métodos para ordinales (rangos o modelos ordinales) |
| Una categoría binaria (aprueba / no aprueba)                     | Regresión logística (lección de multivariado) |

Dos matices para no caer en el extremo opuesto:

Primero, "es defendible tratar el puntaje como continuo" no exime de **comprobar los supuestos** de la
regresión (los del bloque 7). La discusión sobre el nivel de medición es independiente de si los residuos son
normales o la varianza es constante; ambas cosas se revisan igual.

Segundo, la magnitud importa. Con **pocos ítems** (dos o tres) el puntaje tiene todavía pocos valores y el
argumento se debilita; con **muchos ítems** el puntaje es claramente cuasi-continuo y el argumento es fuerte.
No es una frontera exacta, sino un continuo: cuantos más valores distintos tome el puntaje, más sólida es la
vía paramétrica.

En síntesis: la crítica a lo Likert es válida para el ítem suelto, pero no para el puntaje sumado. Rechazar la
regresión lineal "porque los ítems son ordinales" ignora que la suma ya transformó la variable, y descarta sin
motivo una herramienta apropiada. La decisión correcta no se toma por la etiqueta ("Likert"), sino por la
granularidad real de la variable que se va a modelar y por la comprobación de sus supuestos.

> El caso en que la respuesta sí es genuinamente **un solo indicador ordinal con pocas categorías** (un nivel
> de logro, un único ítem) requiere modelos específicos de regresión ordinal. Como en el contexto de esta
> lección lo habitual es trabajar con puntajes sumados, ese enfoque se deja apuntado para la lección de
> análisis multivariado, junto con la regresión logística.

## 10. Reportar los resultados

El paquete `report` funciona también con correlaciones y modelos de regresión, y genera un borrador de
redacción en formato APA:

```r
cor.test(datos$measure_mate, datos$measure_lect) %>% report()
lm(measure_lect ~ measure_mate, data = datos) %>% report()
```

Y `broom::tidy()` entrega los coeficientes como tabla lista para dar formato con `flextable` o `apaTables`.

---

## 11. Síntesis

El recorrido fue:

1. **Correlación**: cuantificar la fuerza y dirección de una relación. Pearson (relación lineal), Spearman
   (monotónica) y Kendall (concordancia entre pares), con r² como medida de varianza compartida y el diagrama
   de dispersión como paso previo obligatorio. Con varias variables, la matriz de correlaciones exige ajustar
   los valores p por comparaciones múltiples.
2. **Regresión lineal simple**: modelar y predecir una variable a partir de otra. Comprobación de los supuestos
   LINE sobre los residuos antes de interpretar; lectura de la pendiente, el intercepto, R², la F y los
   intervalos de confianza; qué hacer cuando un supuesto falla; y la distinción entre intervalo de confianza y
   de predicción.
3. **Escalas Likert**: un puntaje construido sumando ítems se transforma en una variable cuasi-continua, de
   modo que la vía paramétrica (regresión lineal, t, ANOVA) es defendible pese a que los ítems sean ordinales.

Dos ideas transversales: la correlación describe asociación, no causa; y la elección del método (Pearson frente
a Spearman, tratar un puntaje como continuo o no) se decide a partir de la naturaleza de las variables y de la
comprobación de los supuestos, nunca del resultado buscado.

La extensión a **varios predictores a la vez** (regresión múltiple), junto con la **regresión logística** para
respuestas binarias y los **modelos de regresión ordinal** para respuestas de un solo indicador ordinal, se
desarrolla en la lección de análisis multivariado.